<a href="https://colab.research.google.com/github/CyprianKyalo/Machine-Learning/blob/main/Group_2_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [271]:
import numpy as np
import pandas as pd
import math

In [272]:
# Specifying the batch size
batch_size = 2

In [273]:
# Initializing the inputs
data = {'x1': [0.52, 0.3, 0.7, 0.23], 'x2': [-0.2, 0.92, 0.12, -0.1], 'y': [0.6, 0.43, -0.89, 0.58]}
data

{'x1': [0.52, 0.3, 0.7, 0.23],
 'x2': [-0.2, 0.92, 0.12, -0.1],
 'y': [0.6, 0.43, -0.89, 0.58]}

In [274]:
# Converting the data into a dataframe for easier visualization
data = pd.DataFrame(data)
data

x1    x2     y
0  0.52 -0.20  0.60
1  0.30  0.92  0.43
2  0.70  0.12 -0.89
3  0.23 -0.10  0.58

# Creating a class to handle all the computations

In [275]:
class ANN:
  def __init__(self, data, batch_size = data.shape[0]):
    self.data = data
    self.batch_size = batch_size
    self.weight_1 = np.array([[0.3, 0.5, 0.9], [0.7, 0.8, 0.3]])
    self.weight_2 = np.array([[0.12, 0.13, 0.1, 0.3], [0.89, 0.1, 0.2, 0.6], [0.7, 0.6, 0.43, 0.26]])
    self.weight_3 = np.array([0.7, 0.1, 0.4, 0.9])

  # Function to compute tanh
  def tanh(self):
    return (math.exp(self.x) - math.exp(-self.x)) / (math.exp(self.x) + math.exp(-self.x))

  # Function to compute the activation of a layer
  def activate(self, layer):
    new_arr = []
    for x in range(layer.shape[0]):
      inside_arr = []
      for y in layer[x]:
        inside_arr.append(tanh(y))
      new_arr.append(inside_arr)

    return np.array(new_arr)
  
  # Function to compute activated output of the first layer
  def first_layer(self):
    return self.activate(np.dot((self.data.iloc[:self.batch_size, :self.batch_size]).to_numpy(), self.weight_1))

  # Function to compute activated output of the second layer
  def second_layer(self):
    return self.activate(np.dot(self.first_layer(), self.weight_2))

  # Function to compute activated output of the last layer
  def final_layer(self):
    return np.dot(self.second_layer(), self.weight_3)

  # Function to calculate Mean Squared Error
  def MSE(self):
    errors = []
    count = 0
    y_true = np.array(self.data.iloc[:self.batch_size, self.batch_size:]).reshape(1, 2)[0]
    for x, y in zip(y_true, self.final_layer()):
      error = (x - y)**2
      errors.append(error)
      count += 1
    return sum(errors)/count 


In [276]:
ann = ANN(data, batch_size)
# ann.first_layer()
# ann.second_layer()
# ann.final_layer()
print("The Mean Squared Error is", ann.MSE())


The Mean Squared Error is 0.3993754661113965


# Calucating the question Step by Step

#### Initializing the weights

In [277]:
weight_1 = np.array([[0.3, 0.5, 0.9], [0.7, 0.8, 0.3]])
weight_1

array([[0.3, 0.5, 0.9],
       [0.7, 0.8, 0.3]])

In [278]:
weight_2 = np.array([[0.12, 0.13, 0.1, 0.3], [0.89, 0.1, 0.2, 0.6], [0.7, 0.6, 0.43, 0.26]])
weight_2

array([[0.12, 0.13, 0.1 , 0.3 ],
       [0.89, 0.1 , 0.2 , 0.6 ],
       [0.7 , 0.6 , 0.43, 0.26]])

In [279]:
weight_3 = np.array([0.7, 0.1, 0.4, 0.9])
weight_3

array([0.7, 0.1, 0.4, 0.9])

#First Layer

In [280]:
first_layer = np.dot((data.iloc[:batch_size, :batch_size]).to_numpy(), weight_1)
first_layer

array([[0.016, 0.1  , 0.408],
       [0.734, 0.886, 0.546]])

In [281]:
first_layer.shape

(2, 3)

#### activating using tanh 
tanh
=
e^
x
−
e^
−
x/
e^
x
+
e^
−
x


In [282]:
def tanh(x):
  return (math.exp(x) - math.exp(-x)) / (math.exp(x) + math.exp(-x))

In [283]:
def activate(layer):
  new_arr = []
  for x in range(layer.shape[0]):
    inside_arr = []
    for y in layer[x]:
      inside_arr.append(tanh(y))
    new_arr.append(inside_arr)

  return np.array(new_arr)

In [284]:
# activating first layer
first_layer = activate(first_layer)
first_layer

array([[0.01599863, 0.09966799, 0.38677318],
       [0.62550641, 0.70941243, 0.4975163 ]])

# Second Layer

In [285]:
weight_2

array([[0.12, 0.13, 0.1 , 0.3 ],
       [0.89, 0.1 , 0.2 , 0.6 ],
       [0.7 , 0.6 , 0.43, 0.26]])

In [286]:
second_layer = np.dot(first_layer, weight_2)
second_layer

array([[0.36136558, 0.24411053, 0.18784593, 0.16516142],
       [1.05469924, 0.45076685, 0.41836513, 0.74265362]])

In [287]:
# activating the second layer
second_layer = activate(second_layer)
second_layer

array([[0.34641631, 0.23937454, 0.18566723, 0.16367585],
       [0.78362662, 0.42252916, 0.39555225, 0.63074574]])

# Final Layer

In [288]:
weight_3

array([0.7, 0.1, 0.4, 0.9])

In [289]:
final_layer = np.dot(second_layer, weight_3)
final_layer

array([0.48800402, 1.31668362])

# Computing the error
MSE formula = (1/n) * Σ(y_true – y_hat)^2

In [290]:
y_true = np.array(data.iloc[:batch_size, batch_size:]).reshape(1, 2)[0]
y_true

array([0.6 , 0.43])

In [291]:
y_hat = final_layer
y_hat

array([0.48800402, 1.31668362])

In [292]:
def MSE(y_true, y_hat):
  errors = []
  count = 0
  for x, y in zip(y_true, y_hat):
    error = (x - y)**2
    errors.append(error)
    count += 1
  return sum(errors)/count

In [293]:
# The Mean Squared Error
print('The Mean Squared Error is', MSE(y_true, y_hat))

The Mean Squared Error is 0.3993754661113965
